version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: api_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 🧠 this is the persistence layer

volumes:
  mysql_data:  